import { db } from './index.js';
import { recipes, recipeIngredients, recipeSteps, recipeTags, inventory } from './schema.js';

/**
 * Seed script for testing the database setup
 * Run with: tsx src/db/seed.ts
 */

async function seed() {
  console.log('Seeding database...');

  try {
    // Insert a sample recipe
    const [recipe] = await db
      .insert(recipes)
      .values({
        title: 'Simple Pasta',
        description: 'A quick and easy pasta dish',
        prepTimeMinutes: 10,
        cookTimeMinutes: 15,
        servings: 4,
        isFavorite: false,
      })
      .returning();

    console.log('Created recipe:', recipe.title);

    // Insert ingredients for the recipe
    await db.insert(recipeIngredients).values([
      {
        recipeId: recipe.id,
        ingredientName: 'pasta',
        quantity: '1',
        unit: 'lb',
        orderIndex: 0,
      },
      {
        recipeId: recipe.id,
        ingredientName: 'olive oil',
        quantity: '2',
        unit: 'tbsp',
        orderIndex: 1,
      },
      {
        recipeId: recipe.id,
        ingredientName: 'garlic',
        quantity: '3',
        unit: 'cloves',
        notes: 'minced',
        orderIndex: 2,
      },
    ]);

    console.log('Created recipe ingredients');

    // Insert steps for the recipe
    await db.insert(recipeSteps).values([
      {
        recipeId: recipe.id,
        stepNumber: 1,
        instruction: 'Bring a large pot of salted water to a boil',
      },
      {
        recipeId: recipe.id,
        stepNumber: 2,
        instruction: 'Add pasta and cook according to package directions',
      },
      {
        recipeId: recipe.id,
        stepNumber: 3,
        instruction: 'Heat olive oil in a pan and sauté garlic until fragrant',
      },
      {
        recipeId: recipe.id,
        stepNumber: 4,
        instruction: 'Drain pasta and toss with garlic oil',
      },
    ]);

    console.log('Created recipe steps');

    // Insert tags
    await db.insert(recipeTags).values([
      {
        recipeId: recipe.id,
        tag: 'italian',
        isAutoGenerated: false,
      },
      {
        recipeId: recipe.id,
        tag: 'quick',
        isAutoGenerated: false,
      },
    ]);

    console.log('Created recipe tags');

    // Insert some inventory items
    await db.insert(inventory).values([
      {
        ingredientName: 'pasta',
        notes: '2 boxes in pantry',
      },
      {
        ingredientName: 'olive oil',
      },
      {
        ingredientName: 'garlic',
        notes: 'Fresh bulb',
      },
    ]);

    console.log('Created inventory items');

    console.log('\n✓ Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
